from typing import List, Tuple

from manage_tools.widgets.modifier_widget_parent import ModifierWidget
from operators.motlogging import logger
from operators.ws_reader import read_ws


class WsModifyWidget(ModifierWidget):
    ws_list: List[Tuple[int, int, float]]
    file_filter = "*.ws"

    def __init__(self):
        super(WsModifyWidget, self).__init__()

    def open(self, file_path: str):
        self.ws_list = read_ws(file_path)
        return 0

    def save(self, save_path: str):
        try:
            with open(save_path, "w", encoding="utf8") as f:
                f.write("# This file was generated by modifier\n")
                for now_ws_line in self.ws_list:
                    line = f"{now_ws_line[0]}<-{now_ws_line[1]},{now_ws_line[2]}"
                    f.write(line + "\n")

        except IOError as e:
            logger.error("Unable to save ws: " + save_path)
            logger.error(e)
            return -1
        return 0
